version: "3.8"
services:
    traefik:
        image: "traefik:v2.9"
        #container_name: "traefik"
        command:
        #- "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.myresolver.acme.email=info@damagames.com"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        ports:
        - "443:443"
        - "80:80"
        - "8080:8080"
        volumes:
        #- "/letsencrypt:/letsencrypt"
        - letsencrypt-data:/letsencrypt
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

    frontend:
        build: 
            context: ./frontend/
        labels:
        - "traefik.frontend.priority=1"
        - "traefik.enable=true"
        #- "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.${REMOTE_HOST}"
        - "traefik.http.routers.frontend.rule=Host(`${REMOTE_HOST}`) || (Host(`app.${REMOTE_HOST}`))"
        #- "traefik.http.routers.frontend.rule=Host(`damagames.com`) || (Host(`app.damagames.com`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=myresolver"
        - "traefik.http.routers.frontend-http.rule=Host(`${REMOTE_HOST}`) || (Host(`app.${REMOTE_HOST}`))"
        - "traefik.http.routers.frontend-http.entrypoints=web"
        - "traefik.http.middlewares.frontend-http.redirectscheme.scheme=https"


    # PHP services

    api:
        build:
            context: ./backend
            args:
                - APP_ENV
        environment:
            - APP_ENV
            - CONTAINER_ROLE=app
            - DB_CONNECTION
            - DB_HOST
            - DB_PORT
            - DB_DATABASE
            - DB_USERNAME
            - DB_PASSWORD
        ports:
            - 8000:8000
        depends_on:
            - database
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api-http.entrypoints=web"
        #- "traefik.http.routers.api-http.rule=Host(`api.${REMOTE_HOST}`)"
        - "traefik.http.middlewares.api-http.redirectscheme.scheme=https"
        - "traefik.http.routers.api-https.entrypoints=websecure"
        - "traefik.http.routers.api-https.rule=Host(`api.${REMOTE_HOST}`) || PathPrefix(`/api`)"
        - "traefik.http.routers.api-https.middlewares=api-stripprefix"
        - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
        - "traefik.http.routers.api-https.tls.certresolver=myresolver"

    # Database server
    database:
        image: mariadb:10.6
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - SERVICE_TAGS=${APP_ENV}
            - SERVICE_NAME=database
        volumes:
            - mysql-data:/var/lib/mysql

    # Websockets Server
    sockets:
        build:
            context: ./socket
        environment:
            - APP_ENV
            - CONTAINER_ROLE=sockets
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sockets-http.entrypoints=web"
        #- "traefik.http.routers.sockets-http.rule=Host(`sockets.${REMOTE_HOST}`)"
        - "traefik.http.middlewares.sockets-http.redirectscheme.scheme=https"
        - "traefik.http.routers.sockets-https.entrypoints=websecure"
        - "traefik.http.routers.sockets-https.rule=Host(`sockets.${REMOTE_HOST}`) || PathPrefix(`/sockets`)"
        - "traefik.http.routers.sockets-https.middlewares=sockets-stripprefix"
        - "traefik.http.middlewares.sockets-stripprefix.stripprefix.prefixes=/sockets"
        - "traefik.http.routers.sockets-https.tls.certresolver=myresolver"

volumes:
    mysql-data: ~
    letsencrypt-data: ~
