version: "3.8"
services:
    traefik:
        image: "traefik:v2.9"
        container_name: "traefik"
        command:
        #- "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        # - "--certificatesresolvers.myresolver.acme.email=info@damagames.com"
        # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
        - "443:443"
        - "80:80"
        - "8080:8080"
        volumes:
        - "./letsencrypt:/letsencrypt"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

    frontend:
        build: 
            context: ./frontend/
        labels:
        - "traefik.frontend.priority=1"
        - "traefik.enable=true"
        - "traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.${REMOTE_HOST}"
        #- "traefik.http.routers.nginx.rule=Host(`damagames.com`) || (Host(`app.damagames.com`)"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.tls.certresolver=myresolver"
        - "traefik.http.middlewares.nginx-http.redirectscheme.scheme=https"


    # PHP services

    api:
        build:
            context: ./backend
            args:
                - APP_ENV
        environment:
            - APP_ENV
            - CONTAINER_ROLE=app
            - DB_CONNECTION
            - DB_HOST
            - DB_PORT
            - DB_DATABASE
            - DB_USERNAME
            - DB_PASSWORD
        ports:
            - 8082:8082
        depends_on:
            - database
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api-http.entrypoints=web"
        - "traefik.http.routers.api-http.rule=Host(`api.${REMOTE_HOST}`)"
        - "traefik.http.routers.api-https.entrypoints=websecure"
        - "traefik.http.routers.api-https.rule=Host(`api.${REMOTE_HOST}`)"
        - "traefik.http.routers.api-https.tls.certresolver=myresolver"
        - "traefik.http.middlewares.api-https.redirectscheme.scheme=https"

    # Database server
    database:
        image: mariadb:10.6
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - SERVICE_TAGS=${APP_ENV}
            - SERVICE_NAME=database
        volumes:
            - mysql-data:/var/lib/mysql

    # Websockets Server
    socket:
        build:
            context: ./socket
        environment:
            - APP_ENV
            - CONTAINER_ROLE=sockets

volumes:
    mysql-data: ~
