version: "3.8"
services:
    traefik:
        image: "traefik:v2.9"
        container_name: "traefik"
        command:
        #- "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
        - "--certificatesresolvers.myresolver.acme.email=info@damagames.com"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
        - "443:443"
        - "80:80"
        volumes:
        - "./letsencrypt:/letsencrypt"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

    nginx-frontend:
        build: 
            context: ./dama-frontend/
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(`damagames.com`)"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.tls.certresolver=myresolver"
        - "traefik.http.routers.nginx-http.entrypoints=web"
        - "traefik.http.routers.nginx-http.rule=Host(`damagames.com`)"
        - "traefik.http.middlewares.nginx-https.redirectscheme.scheme=https"


    # PHP services

    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV
        environment:
            - APP_ENV
            - CONTAINER_ROLE=app
            - DB_CONNECTION
            - DB_HOST
            - DB_PORT
            - DB_DATABASE
            - DB_USERNAME
            - DB_PASSWORD
            - REDIS_PASSWORD
        working_dir: /var/www
        #volumes:
        #    - ./:/var/www
        ports:
            - 8007:8007
        depends_on:
            - database
            - redis
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api-http.entrypoints=web"
        - "traefik.http.routers.api-http.rule=Host(`api.damagames.com`)"
        - "traefik.http.routers.api-https.entrypoints=websecure"
        - "traefik.http.routers.api-https.rule=Host(`api.damagames.com`)"
        - "traefik.http.routers.api-https.tls.certresolver=myresolver"
        - "traefik.http.middlewares.api-https.redirectscheme.scheme=https"

    # Database server
    database:
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            - 6385:6378

    # Queue Server
    queue:
        build:
            context: .
            target: php
            args:
                - APP_ENV
        environment:
            - APP_ENV
            - CONTAINER_ROLE=queue
        working_dir: /var/www
        #volumes:
        #    - ./:/var/www

volumes:
    mysql-data: ~
