version: "3.8"
services:
    # PHP services
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        container_name: dama
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8007:8007
        depends_on:
            - database
            - redis
    # Database server
    database:
        image: mysql:latest
        restart: always
        ports:
            - 3320:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - dama-data:/var/lib/mysql
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            - 6386:6378

volumes:
    dama-data: ~ 
