:jbake-title: Runtime View
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 6
:filename: /chapters/06_runtime_view.adoc
ifndef::imagesdir[:imagesdir: ../../images]

:toc:

[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****

=== Player sign-up / sign-in

.Player signs up or signs in
[plantuml, "{plantUMLDir}runtime_scenario_0", png] 
----
@startuml
autonumber

actor Player as "Player browser"
participant httpd
boundary Frontend as Frontend
participant API

Player -> httpd : https://dama.et \nGET /
httpd -> Player : 200 serve Frontend
Player -> Frontend : start matchmaking \nstart private game
Frontend -> API : POST /games
API -> API : authenticated: \nfalse
API -> Frontend : redirect /login \nwith callback_uri \n and state to \nPOST /games \nafter redirect
Frontend -> Player : Sign-up / Sign-in page
Player -> Frontend : Sign-up
Frontend -> API : POST /users/
API -> Frontend : 201 success \n redirect to main screen
Frontend -> Frontend : get state \nshow loading animation
Frontend -> Player : Start screen with loading animation
Frontend -> API : POST /games
API -> API : authenticated \n && authorized \ntrue
API -> Frontend : 201 success
Frontend -> Player : waiting for Player \nshare private game URL

@enduml
----

=== Player creates a game

.Player creates a private game
[plantuml, "{plantUMLDir}runtime_scenario_1", png] 
----
@startuml
autonumber
boundary messenger as "WhatsApp/Telegram"
actor Player as Player
boundary Frontend as Frontend
participant game_endpoint as "/games"

Player -> Frontend : Clicks "Create private game"
Frontend -> game_endpoint : POST create game
game_endpoint -> Frontend : 201 /games/{id}
Frontend -> Player : shareable link to game
Player -> messenger : shares link with friend
@enduml
----


* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

=== New player joining a game

.New player joins a game
[plantuml, "{plantUMLDir}runtime_scenario_2", png] 
----
@startuml
autonumber
boundary messenger as "WhatsApp/Telegram"
actor Player as Player
boundary Frontend as Frontend
participant game_endpoint as "/games/{id}"
participant user_endpoint as "auth"

Player <- messenger : receives link from friend
Player -> Frontend : Open https://dama.et/games/{id}
Frontend -> game_endpoint : POST /games/{id}/player2 to join game
game_endpoint -> game_endpoint : is user authenticated\n false
game_endpoint -> Frontend : unauthenticated session\n with state set for "start-game"\n with the game ID \nredirect to /login
Frontend -> user_endpoint : GET
user_endpoint -> Frontend : 200 sign-up / sign-in page
Frontend -> user_endpoint : POST sign-up form (just username for now)
user_endpoint -> Frontend : 201 authenticated session
Frontend -> Frontend : get state \nshow loading animation
Frontend -> game_endpoint : POST /games/{id}/player2 to join game
game_endpoint -> Frontend : 201 game
Frontend -> Player : Game has started
@enduml
----

=== Two players playing

.New player joins a game
[plantuml, "{plantUMLDir}runtime_scenario_2", png] 
----
@startuml
autonumber

actor Player1 as Player1
boundary frontend as frontend
participant board_endpoint as "/games/{id}/board"
participant move_endpoint as "/games/{id}/moves/{seq}"
actor Player2 as Player2


Player1 -> frontend : started game
frontend -> board_endpoint : GET /games/{id}/board
board_endpoint -> frontend : 200 board state \n{ next player \nnext move seq }
frontend -> Player1 : render board state
Player1 -> frontend : make move
frontend -> move_endpoint : POST /games/{id}/moves/{seq}
move_endpoint -> frontend : 201
frontend -> Player1 : move confirmed \nwait for opponents move
frontend -> move_endpoint : GET /games/{id}/moves/{seq+1} \nretry when timeout
Player2 -> move_endpoint : POST /games/{id}/moves/{seq}
move_endpoint -> frontend : 200 Player 2 move
frontend -> Player1 : render opponent move \nwait for Player1 move
@enduml
----