:jbake-title: Architecture Decisions
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 9
:filename: /chapters/09_architecture_decisions.adoc
ifndef::imagesdir[:imagesdir: ../../images]

:toc:

[[section-design-decisions]]
== Architecture Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****

=== ADR 1: Developing a PWA

*Context*

Also refer to xref:04_solution_strategy.adoc[Solution Strategy]

PWA as alternative to developing a native App.

They are easier for developers to deploy, update and roll back.

For users they offer easy sharing of game via a link, quick onboarding of new users without installation of an app and good device compatibility.

*Decision*

Date: 25.11.2022

We chose to develop DAMA as a Progressive Web App.

*Status*

Accepted

*Consequences*

Team needs PWA and HTML5 skills.

=== ADR 2: Developing a REST API

*Context*

REST APIs are best practice for developing APIs. 

However for online multiplayer games, especially real time strategy games, often web sockets or messaging queues are preferred, because they offer fast user-action distribution, sometimes also pub/sub features and improved scalability.

On the other side, especially for a game with a web based frontend, server-side checks of legality of moves are required, which reduce the usefulness of a message queue architecture.

*Decision*

We chose to develop a REST API.

This serves the current requirements and enables short time-to-market. 

Through clearly defined interfaces and message objects (Postman collection), we enable a potential future migration of the client-server communication, should the scalability and performance requirements make it necessary in the future.

*Status*

In review

*Consequences*

- Team needs REST API development skills

****

=== ADR n: Architecture Decision Record Template

*Context*

*Decision*

*Status*

*Consequences*

****