---
name: 'Deploy Docker Containers'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        #name: id_rsa # optional
        known_hosts: ${{ env.SSH_FINGERPRINT }}
        #config: ${{ secrets.CONFIG }} # ssh_config; optional
        #if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

    - name: Create docker context
      run: docker context create prod --docker "host=ssh://${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}"

    # - name: Remove old php container to force build
    #   run: docker-compose --context prod -f docker-compose.prod.yml rm -s -f

    # - name: Stop containers
    #   run: docker-compose --context prod -f docker-compose.prod.yml down --remove-orphans

    - name: Deploy Docker Containers
      run: |
        docker-compose --context prod -f docker-compose.prod.yml up --build -d
      env:
        DOCKER_HOST: ssh://${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}
        #DOCKER_TLS_VERIFY: 1
        #DOCKER_CERT_PATH: /github/workspace/.ssh
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
