---
name: "build, release and deploy"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v*-rc[0-9]+"

jobs:

  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Prune Docker system
      run: sudo docker system prune -af
      
  deploy_staging:
    uses: ./.github/workflows/docker_stage.yml
    secrets: inherit
    needs: "cleanup"

  deploy_production:
    if: ${{ !contains(github.ref, '-rc') }}
    uses: ./.github/workflows/docker_deploy.yml
    secrets: inherit
    needs: "deploy_staging"
