---
name: "build, release and deploy"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v*-rc[0-9]+"

jobs:

  cleanup:
   #run cleanup only is size greater than or equal 3gb == 3221225472 bytes
    if: ${{ (fromJSON(run: 'sudo docker system df --format "{{.Size}}" | head -n 1') | int) >= 3221225472 }}
    runs-on: ubuntu-latest
    steps:
    - name: Prune Docker system
      run: sudo docker system prune -af
      
  deploy_staging:
    uses: ./.github/workflows/docker_stage.yml
    secrets: inherit
    needs: "cleanup"

  deploy_production:
    if: ${{ !contains(github.ref, '-rc') }}
    uses: ./.github/workflows/docker_deploy.yml
    secrets: inherit
    needs: "deploy_staging"
