---
name: 'build, release and deploy'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v*-rc[0-9]+'

jobs:
  build_arc_docs:
    uses: ./.github/workflows/build_arc_docs.yml

  release:
    uses: ./.github/workflows/release.yml
    needs: ['build_arc_docs','e2e-test']
  # with:
  #   secrets:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_staging:
    uses: ./.github/workflows/docker_stage.yml
    secrets: inherit
    #needs: 'release'

  deploy_production:
    uses: ./.github/workflows/docker_deploy.yml
    secrets: inherit
    # needs: 'release'


  e2e-test:
    uses: ./.github/workflows/playwright.yml
    secrets: inherit
    needs: 'deploy_production'
