name: Playwright Tests
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
<<<<<<< HEAD
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
=======
    - name: zip report folder
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r playwright_report-${{ env.RELEASE_VERSION }}.zip playwright-report/
    - name: Upload playwright report for release
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright_report-${{ env.RELEASE_VERSION }}.zip
>>>>>>> 1d2d8b3d3812a36082b0828ecfe8add7575b947d
        retention-days: 30
